In [6]:
import numpy as np

I = [1,2,3,4]
x = np.array(I)

type(x)
x.ndim
x.shape
np.arange(0,11,2,dtype='float')
np.linspace(0,5,5)
np.random.rand(2)
N=np.random.rand(2,3)
N

array([[5.62655872e-01, 9.14078702e-01, 6.81487390e-01],
       [3.14809383e-04, 3.47789515e-01, 6.47117751e-02]])

In [7]:
N.max()

0.9140787022555361

In [9]:
N.min()

0.0003148093830754872

In [10]:
N.sum()

2.571038063392369

In [12]:
N.mean()

0.42850634389872816

In [14]:
N.argmax()

1

In [21]:
np.random.randint(1,7)

3

In [22]:
np.random.randint(1,100,(3,4))

array([[38, 80, 83, 78],
       [47, 78, 47, 77],
       [59, 63, 71, 45]])

In [23]:
m=np.array(([5,10,15],[20,25,30],[35,40,45]))
m

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
m[2]

array([35, 40, 45])

In [25]:
m[2][0]

35

In [26]:
m[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [27]:
m[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
m[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [29]:
m[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [30]:
m[-1][0]

35